# action.yml
name: 'Toumoro Slack Messaging'
description: 'Interactive messaging services for Slack'
author: 'Benoit Verret TM <benoit.verret@toumoro.com'
inputs:
  api_url:
    description: 'API URL handling the messaging system.'
    required: true
  api_key:
    description: 'API KEY for authentication.'
    required: true
  service:
    description: 'Service using this action as 'github', 'gitlab', 'bitbucket'.'
    required: true
  project:
    description: 'Name of the project.'
    required: true
  channel:
    description: 'Slack channel to post the message.'
    required: true
  ref:
    description: 'Repo reference as GITHUB_REF, 'refs/head/master', ...'
    required: true
  run_id:
    description: 'Runner ID as GITHUB_RUN_ID.'
    required: true
  step:
    description: 'Step triggering the call.'
    required: true
  type:
    description: 'Message type. ('error', 'request', 'status').'
    required: true
  status:
    description: 'Inline status following the regex `(?(DEFINE)(?<status>\w*:(?:FAIL|PASS)))^(?&status)(?:;(?&status))*$` as `Build:PASS;Test:FAIL`.'
    required: true
  issue_id:
    description: 'Issue ID for internal reference.'
    required: true
  actor:
    description: 'Trigger Actor as GITHUB_ACTOR.'
    required: true
  repository:
    description: 'Repository as GITHUB_REPOSITORY, 'user/project'.'
    required: true
  workflow:
    description: 'Workflow reference for manual triggering, for GitHub it represent the workflow file name.'
    required: false
  timestamp:
    description: 'Slack timestamp for editing a previous message.'
    required: false
  verbose:
    description: 'Level of verbose, options: ['0', '1', '2']. '
    required: false
    default: '0'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon:  'message-square'
  color: 'green'
