FROM github/super-linter:latest

LABEL version="1.0.0"
LABEL organization="Toumoro"
LABEL homepage="https://toumoro.com/"
LABEL maintainer="Benoit Verret <benoit.verret@toumoro.com>"
LABEL repository="https://github.com/toumoto/cicd-tools/tree/master/super-linter-action"
