name: Lint Cloudflare Purge Action Report

on:
  push:
    branches:
      - master
    paths:
      - 'cloudflare-purge-action/**/*'

jobs:
  lint:
    name: Lint Cloudflare Purge Action Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          RUN_LOCAL: 'true'
          DEFAULT_WORKSPACE: ./cloudflare-purge-action
