name: Lint Slack Messaging Report

on:
  push:
    branches:
      - master
    paths:
      - 'slack-messaging-action/**/*'

jobs:
  build:
    name: Lint Slack Messaging Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          RUN_LOCAL: 'true'
          DEFAULT_WORKSPACE: ./slack-messaging-action
