name: Update SSH Commands Action Description

# FIXME: Updating DockerHub Repository Description
# This action need a user with full admin right and not a PAT
# https://github.com/docker/roadmap/issues/115

on:
  push:
    branches:
      - 'no-implemented'
    paths:
      - 'ssh-commands-action/README.md'

jobs:
  docs:
    name: Update Description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update SSH Commands Action Description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: toumoro/ssh-commands-action
          README_FILEPATH: ./ssh-commands-action/README.md
