name: Update Super-Linter Action Description

# FIXME: Updating DockerHub Repository Description
# This action need a user with full admin right and not a PAT
# Working on a solution ...

on:
  push:
    branches:
      - 'no-implemented'
    paths:
      - 'super-linter-action/README.md'

jobs:
  docs:
    name: Update Description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Super-Linter Action Description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: toumoro/super-linter-action
          README_FILEPATH: ./super-linter-action/README.md
